#Database details
database:
  # A Data Source Name (dsn) is a connection string of the form:
  # driver://username:password@hostname/databasename
  dsn: mysql://root:@localhost/cms_innodb
  prefix: cms_

#Should we be in debug mode?
debug: false

#Places to look for classes when autoloading
class_autoload:
  - app/models
